# Namespace name will be set via --set namespace.name in CI/CD
namespace:
  name: ""

ingress:
  className: traefik
  host: ""
  rules:
    - paths:
        - path: /
          serviceName: frontend-service
          servicePort: 8080
