# Namespace name will be set via --set namespace.name in CI/CD
namespace:
  name: ""

ingress:
  className: traefik
  rules:
    - host: dracocheng.com
      paths:
        - path: /
          serviceName: frontend-service
          servicePort: 8080
